[package]
name = "pdfunite-trees"
version = "0.1.0"
authors = ["Carlo Lanzi Luciani <carlolanziluciani@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = {version = "4.5.0", features = ["derive"]}
lopdf = "0.36.0"
rand = "0.9.1"
