[package]
name = "pdfunite-tree"
version = "0.1.0"
authors = ["Carlo Lanzi Luciani <carlolanziluciani@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = {version = "4.5.0", features = ["derive"]}
printpdf = "0.8.2"
